# mariadb configuration properties
spring:
  datasource:
    url: jdbc:mariadb://localhost:3304/running_wishes
    username: root
    password: mypass
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update

  # KAFKA config
  kafka:
    consumer:
      group-id: custom
#     the consumers will start reading messages from the earliest one available
#     when there is no existing offset for that consumer.
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092


  jackson:
    serialization:
      write-dates-as-timestamps: false
  hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# port on which springboot application is running
server:
  port: 8090

running-wishes:
  topic-name: upcomingCompetitions
#  messages-per-request: 10

# keycloak properties
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: running-wishes
# resource = name of the application on the Keycloak server
  resource: running-wishes-client
  public-client: true
  bearer-only: true

my:
  keycloak:
    url: http://localhost:8080
    auth:
      endpoint: auth/realms/running-wishes/protocol/openid-connect/token

    admin:
      username: admin
      password: passwor
      client: admin-cli
      realm: master

security:
  config:
    bearer: true
    authcode-flow: false